name: Lint Node.js Server

on:
  push:
    branches:
      - '**' 
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Set the desired Node.js version

      # Install dependencies
      - name: Install dependencies
        run: |
          npm ci  # Use `npm install` if you're not using a lock file

      # Run ESLint
      - name: Run ESLint
        run: npm run lint  # Assumes you have a lint script in package.json
